# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aleksandrivanov/Sandbox/Books/OpenGL_SuperBible/SBCode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aleksandrivanov/GoogleDrive/Sandbox/Books/OpenGL_SuperBible/SBCode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.9.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aleksandrivanov/GoogleDrive/Sandbox/Books/OpenGL_SuperBible/SBCode/CMakeFiles /Users/aleksandrivanov/GoogleDrive/Sandbox/Books/OpenGL_SuperBible/SBCode/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aleksandrivanov/GoogleDrive/Sandbox/Books/OpenGL_SuperBible/SBCode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named basic_shaders

# Build rule for target.
basic_shaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_shaders
.PHONY : basic_shaders

# fast build rule for target.
basic_shaders/fast:
	$(MAKE) -f CMakeFiles/basic_shaders.dir/build.make CMakeFiles/basic_shaders.dir/build
.PHONY : basic_shaders/fast

#=============================================================================
# Target rules for targets named basic_animation

# Build rule for target.
basic_animation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_animation
.PHONY : basic_animation

# fast build rule for target.
basic_animation/fast:
	$(MAKE) -f CMakeFiles/basic_animation.dir/build.make CMakeFiles/basic_animation.dir/build
.PHONY : basic_animation/fast

#=============================================================================
# Target rules for targets named basic_app

# Build rule for target.
basic_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_app
.PHONY : basic_app

# fast build rule for target.
basic_app/fast:
	$(MAKE) -f CMakeFiles/basic_app.dir/build.make CMakeFiles/basic_app.dir/build
.PHONY : basic_app/fast

#=============================================================================
# Target rules for targets named sb7

# Build rule for target.
sb7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sb7
.PHONY : sb7

# fast build rule for target.
sb7/fast:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/build
.PHONY : sb7/fast

src/basic_animation/basic_animation.o: src/basic_animation/basic_animation.cpp.o

.PHONY : src/basic_animation/basic_animation.o

# target to build an object file
src/basic_animation/basic_animation.cpp.o:
	$(MAKE) -f CMakeFiles/basic_animation.dir/build.make CMakeFiles/basic_animation.dir/src/basic_animation/basic_animation.cpp.o
.PHONY : src/basic_animation/basic_animation.cpp.o

src/basic_animation/basic_animation.i: src/basic_animation/basic_animation.cpp.i

.PHONY : src/basic_animation/basic_animation.i

# target to preprocess a source file
src/basic_animation/basic_animation.cpp.i:
	$(MAKE) -f CMakeFiles/basic_animation.dir/build.make CMakeFiles/basic_animation.dir/src/basic_animation/basic_animation.cpp.i
.PHONY : src/basic_animation/basic_animation.cpp.i

src/basic_animation/basic_animation.s: src/basic_animation/basic_animation.cpp.s

.PHONY : src/basic_animation/basic_animation.s

# target to generate assembly for a file
src/basic_animation/basic_animation.cpp.s:
	$(MAKE) -f CMakeFiles/basic_animation.dir/build.make CMakeFiles/basic_animation.dir/src/basic_animation/basic_animation.cpp.s
.PHONY : src/basic_animation/basic_animation.cpp.s

src/basic_app/basic_app.o: src/basic_app/basic_app.cpp.o

.PHONY : src/basic_app/basic_app.o

# target to build an object file
src/basic_app/basic_app.cpp.o:
	$(MAKE) -f CMakeFiles/basic_app.dir/build.make CMakeFiles/basic_app.dir/src/basic_app/basic_app.cpp.o
.PHONY : src/basic_app/basic_app.cpp.o

src/basic_app/basic_app.i: src/basic_app/basic_app.cpp.i

.PHONY : src/basic_app/basic_app.i

# target to preprocess a source file
src/basic_app/basic_app.cpp.i:
	$(MAKE) -f CMakeFiles/basic_app.dir/build.make CMakeFiles/basic_app.dir/src/basic_app/basic_app.cpp.i
.PHONY : src/basic_app/basic_app.cpp.i

src/basic_app/basic_app.s: src/basic_app/basic_app.cpp.s

.PHONY : src/basic_app/basic_app.s

# target to generate assembly for a file
src/basic_app/basic_app.cpp.s:
	$(MAKE) -f CMakeFiles/basic_app.dir/build.make CMakeFiles/basic_app.dir/src/basic_app/basic_app.cpp.s
.PHONY : src/basic_app/basic_app.cpp.s

src/basic_shaders/basic_shaders.o: src/basic_shaders/basic_shaders.cpp.o

.PHONY : src/basic_shaders/basic_shaders.o

# target to build an object file
src/basic_shaders/basic_shaders.cpp.o:
	$(MAKE) -f CMakeFiles/basic_shaders.dir/build.make CMakeFiles/basic_shaders.dir/src/basic_shaders/basic_shaders.cpp.o
.PHONY : src/basic_shaders/basic_shaders.cpp.o

src/basic_shaders/basic_shaders.i: src/basic_shaders/basic_shaders.cpp.i

.PHONY : src/basic_shaders/basic_shaders.i

# target to preprocess a source file
src/basic_shaders/basic_shaders.cpp.i:
	$(MAKE) -f CMakeFiles/basic_shaders.dir/build.make CMakeFiles/basic_shaders.dir/src/basic_shaders/basic_shaders.cpp.i
.PHONY : src/basic_shaders/basic_shaders.cpp.i

src/basic_shaders/basic_shaders.s: src/basic_shaders/basic_shaders.cpp.s

.PHONY : src/basic_shaders/basic_shaders.s

# target to generate assembly for a file
src/basic_shaders/basic_shaders.cpp.s:
	$(MAKE) -f CMakeFiles/basic_shaders.dir/build.make CMakeFiles/basic_shaders.dir/src/basic_shaders/basic_shaders.cpp.s
.PHONY : src/basic_shaders/basic_shaders.cpp.s

src/sb7/gl3w.o: src/sb7/gl3w.c.o

.PHONY : src/sb7/gl3w.o

# target to build an object file
src/sb7/gl3w.c.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/gl3w.c.o
.PHONY : src/sb7/gl3w.c.o

src/sb7/gl3w.i: src/sb7/gl3w.c.i

.PHONY : src/sb7/gl3w.i

# target to preprocess a source file
src/sb7/gl3w.c.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/gl3w.c.i
.PHONY : src/sb7/gl3w.c.i

src/sb7/gl3w.s: src/sb7/gl3w.c.s

.PHONY : src/sb7/gl3w.s

# target to generate assembly for a file
src/sb7/gl3w.c.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/gl3w.c.s
.PHONY : src/sb7/gl3w.c.s

src/sb7/sb7.o: src/sb7/sb7.cpp.o

.PHONY : src/sb7/sb7.o

# target to build an object file
src/sb7/sb7.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7.cpp.o
.PHONY : src/sb7/sb7.cpp.o

src/sb7/sb7.i: src/sb7/sb7.cpp.i

.PHONY : src/sb7/sb7.i

# target to preprocess a source file
src/sb7/sb7.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7.cpp.i
.PHONY : src/sb7/sb7.cpp.i

src/sb7/sb7.s: src/sb7/sb7.cpp.s

.PHONY : src/sb7/sb7.s

# target to generate assembly for a file
src/sb7/sb7.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7.cpp.s
.PHONY : src/sb7/sb7.cpp.s

src/sb7/sb7color.o: src/sb7/sb7color.cpp.o

.PHONY : src/sb7/sb7color.o

# target to build an object file
src/sb7/sb7color.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7color.cpp.o
.PHONY : src/sb7/sb7color.cpp.o

src/sb7/sb7color.i: src/sb7/sb7color.cpp.i

.PHONY : src/sb7/sb7color.i

# target to preprocess a source file
src/sb7/sb7color.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7color.cpp.i
.PHONY : src/sb7/sb7color.cpp.i

src/sb7/sb7color.s: src/sb7/sb7color.cpp.s

.PHONY : src/sb7/sb7color.s

# target to generate assembly for a file
src/sb7/sb7color.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7color.cpp.s
.PHONY : src/sb7/sb7color.cpp.s

src/sb7/sb7ktx.o: src/sb7/sb7ktx.cpp.o

.PHONY : src/sb7/sb7ktx.o

# target to build an object file
src/sb7/sb7ktx.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7ktx.cpp.o
.PHONY : src/sb7/sb7ktx.cpp.o

src/sb7/sb7ktx.i: src/sb7/sb7ktx.cpp.i

.PHONY : src/sb7/sb7ktx.i

# target to preprocess a source file
src/sb7/sb7ktx.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7ktx.cpp.i
.PHONY : src/sb7/sb7ktx.cpp.i

src/sb7/sb7ktx.s: src/sb7/sb7ktx.cpp.s

.PHONY : src/sb7/sb7ktx.s

# target to generate assembly for a file
src/sb7/sb7ktx.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7ktx.cpp.s
.PHONY : src/sb7/sb7ktx.cpp.s

src/sb7/sb7object.o: src/sb7/sb7object.cpp.o

.PHONY : src/sb7/sb7object.o

# target to build an object file
src/sb7/sb7object.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7object.cpp.o
.PHONY : src/sb7/sb7object.cpp.o

src/sb7/sb7object.i: src/sb7/sb7object.cpp.i

.PHONY : src/sb7/sb7object.i

# target to preprocess a source file
src/sb7/sb7object.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7object.cpp.i
.PHONY : src/sb7/sb7object.cpp.i

src/sb7/sb7object.s: src/sb7/sb7object.cpp.s

.PHONY : src/sb7/sb7object.s

# target to generate assembly for a file
src/sb7/sb7object.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7object.cpp.s
.PHONY : src/sb7/sb7object.cpp.s

src/sb7/sb7shader.o: src/sb7/sb7shader.cpp.o

.PHONY : src/sb7/sb7shader.o

# target to build an object file
src/sb7/sb7shader.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7shader.cpp.o
.PHONY : src/sb7/sb7shader.cpp.o

src/sb7/sb7shader.i: src/sb7/sb7shader.cpp.i

.PHONY : src/sb7/sb7shader.i

# target to preprocess a source file
src/sb7/sb7shader.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7shader.cpp.i
.PHONY : src/sb7/sb7shader.cpp.i

src/sb7/sb7shader.s: src/sb7/sb7shader.cpp.s

.PHONY : src/sb7/sb7shader.s

# target to generate assembly for a file
src/sb7/sb7shader.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7shader.cpp.s
.PHONY : src/sb7/sb7shader.cpp.s

src/sb7/sb7textoverlay.o: src/sb7/sb7textoverlay.cpp.o

.PHONY : src/sb7/sb7textoverlay.o

# target to build an object file
src/sb7/sb7textoverlay.cpp.o:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7textoverlay.cpp.o
.PHONY : src/sb7/sb7textoverlay.cpp.o

src/sb7/sb7textoverlay.i: src/sb7/sb7textoverlay.cpp.i

.PHONY : src/sb7/sb7textoverlay.i

# target to preprocess a source file
src/sb7/sb7textoverlay.cpp.i:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7textoverlay.cpp.i
.PHONY : src/sb7/sb7textoverlay.cpp.i

src/sb7/sb7textoverlay.s: src/sb7/sb7textoverlay.cpp.s

.PHONY : src/sb7/sb7textoverlay.s

# target to generate assembly for a file
src/sb7/sb7textoverlay.cpp.s:
	$(MAKE) -f CMakeFiles/sb7.dir/build.make CMakeFiles/sb7.dir/src/sb7/sb7textoverlay.cpp.s
.PHONY : src/sb7/sb7textoverlay.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... release"
	@echo "... debug"
	@echo "... basic_shaders"
	@echo "... basic_animation"
	@echo "... edit_cache"
	@echo "... basic_app"
	@echo "... sb7"
	@echo "... src/basic_animation/basic_animation.o"
	@echo "... src/basic_animation/basic_animation.i"
	@echo "... src/basic_animation/basic_animation.s"
	@echo "... src/basic_app/basic_app.o"
	@echo "... src/basic_app/basic_app.i"
	@echo "... src/basic_app/basic_app.s"
	@echo "... src/basic_shaders/basic_shaders.o"
	@echo "... src/basic_shaders/basic_shaders.i"
	@echo "... src/basic_shaders/basic_shaders.s"
	@echo "... src/sb7/gl3w.o"
	@echo "... src/sb7/gl3w.i"
	@echo "... src/sb7/gl3w.s"
	@echo "... src/sb7/sb7.o"
	@echo "... src/sb7/sb7.i"
	@echo "... src/sb7/sb7.s"
	@echo "... src/sb7/sb7color.o"
	@echo "... src/sb7/sb7color.i"
	@echo "... src/sb7/sb7color.s"
	@echo "... src/sb7/sb7ktx.o"
	@echo "... src/sb7/sb7ktx.i"
	@echo "... src/sb7/sb7ktx.s"
	@echo "... src/sb7/sb7object.o"
	@echo "... src/sb7/sb7object.i"
	@echo "... src/sb7/sb7object.s"
	@echo "... src/sb7/sb7shader.o"
	@echo "... src/sb7/sb7shader.i"
	@echo "... src/sb7/sb7shader.s"
	@echo "... src/sb7/sb7textoverlay.o"
	@echo "... src/sb7/sb7textoverlay.i"
	@echo "... src/sb7/sb7textoverlay.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

